# For preprocessing information retrieval data (task specific)
## Samples of format : query, document text

In [ ]:
!pip3 install argparse
!pip3 install numpy
!pip3 install pandas
!pip3 install torch
!pip3 install nltk
!pip3 install -U scikit-learn
!pip3 install transformers
!pip3 install datasets

Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
import os
import json
import re
import string
import random
import time
import datetime

import numpy as np
import pandas as pd

from argparse import Namespace
from tqdm import tqdm_notebook
from datasets import Dataset

import transformers
from transformers import BertTokenizer, BertModel
from transformers import AutoTokenizer, AutoModelForMaskedLM

import torch.nn.functional as F
import torch

from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity, linear_kernel

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Configurations

In [1]:
args = Namespace(
    raw_data_filename = 'aus_sum_cases_train.json',
    raw_data_path = "/content/drive/MyDrive/Colab_Notebooks/CS4099-LegalNLP/raw_data/",
    processed_data_path = "/content/drive/MyDrive/Colab_Notebooks/CS4099-LegalNLP/processed_data/sentence-pair.csv",
    max_segment_length = 512,
    stride = 128,
    segment_method = 'sym-trunc', # sym-trunc, lex-trunc, start-trunc, end-trunc
    max_samples = 10,
    mode = 'a', # a : append, w : write,
    train_split = 0.7,
)

NameError: name 'Namespace' is not defined

Load & Process Raw Data

In [ ]:
with open(args.raw_data_path + args.raw_data_filename, 'r') as json_file:
    json_data = json.load(json_file)

In [ ]:
def split_text_generator(paragraph, max_length=512):
    '''
      Takes a paragraph of text and splits into sections of length less than specific limit max_length
      Creates a generator over the subsections
    '''
    def find_split_index(s, start):
        end = min(start + max_length, len(s))
        split_index = s.rfind(' ', start, end)
        return split_index if split_index != -1 else end

    start = 0
    while start < len(paragraph):
        split_index = find_split_index(paragraph, start)
        yield paragraph[start:split_index].strip()
        start = split_index + 1 if split_index < len(paragraph) else len(paragraph)


def split_paragraph_list(paragraph, max_length=512, stride=128):
    '''
      Takes a paragraph of text and splits into sections of length less than specific limit max_length with a specific stride
      Returns the subsections as a list
    '''
    def find_split_index(s, start):
        end = min(start + max_length, len(s))

        if end == len(s): return len(s)

        split_index = s.rfind(' ', start, end)
        return split_index if split_index != -1 else end

    sections = []
    start = 0
    while start < len(paragraph):
        split_index = find_split_index(paragraph, start)
        sections.append(paragraph[start:split_index].strip())
        # start = split_index + 1 if split_index < len(paragraph) else len(paragraph)

        if start + stride >= len(paragraph) or split_index >= len(paragraph): break

        next_start = paragraph.rfind(' ', start, start+stride)

        start = next_start + 1 if next_start != -1 else len(paragraph)

    return sections

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
model.to(device)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

cuda

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=768, out_features=3072, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=3072, out_features=768, bias=True)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (activation): Tanh()
  )
)

Setup TF-IDF over corpus

In [ ]:
stopwords = list(text.ENGLISH_STOP_WORDS)

vectorizer = TfidfVectorizer(stop_words=stopwords, token_pattern=r'\b[^\d\W]+\b')

tfidf = vectorizer.fit_transform([obj['text'] for obj in json_data[0 : 10]])

In [ ]:
def text_similarity(main_text, text_list):

  # Encode the main text
  inputs_main = tokenizer(main_text, return_tensors='pt', truncation=True, max_length=512)
  with torch.no_grad():
      outputs_main = model(**inputs_main)
  embedding_main = outputs_main.last_hidden_state[:, 0, :]

  max_similarity = -1
  most_similar_text = None

  for text in text_list:
      # Encode each text in the list
      inputs = tokenizer(text, return_tensors='pt', truncation=True, max_length=512)
      with torch.no_grad():
          outputs = model(**inputs)

      # Get the [CLS] embeddings
      embedding = outputs.last_hidden_state[:, 0, :]

      # Compute similarity
      similarity = F.cosine_similarity(embedding_main, embedding)
      if similarity > max_similarity:
          max_similarity = similarity
          most_similar_text = text

  return most_similar_text

def lexical_text_similarity(main_text, text_list):
  query_vector = vectorizer.transform([main_text])

  tfidf_list = vectorizer.transform(text_list)

  similarities = linear_kernel(query_vector, tfidf_list).flatten()

  ranked_documents = [(text_list[i], score) for i, score in enumerate(similarities) if score > 0]
  ranked_documents.sort(key=lambda x: x[1], reverse=True)

  if len(ranked_documents):
    return ranked_documents[0]
  else :
    return text_list[0]

In [ ]:
def clean_text(text):
  text = re.sub(r'\s+', ' ', text)

  # # Pattern for document identifiers
  # doc_id_pattern = r'\b\d{1,3}\sU\.S\.C\.\s\d{1,5}\([a-zA-Z0-9]+\)'

  # # Pattern for list numbers
  # list_number_pattern = r'\(\d+\)'

  # # Replace document identifiers
  # text = re.sub(doc_id_pattern, '<DOC_ID>', text)

  # # Replace list numbers
  # text = re.sub(list_number_pattern, '<LIST_NUM>', text)

  return text.strip()

In [ ]:
progress_bar = tqdm_notebook(desc='data processing routine', total=args.max_samples, position=0, leave=True)

<ipython-input-11-1080f343b2b6>:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  progress_bar = tqdm_notebook(desc='data processing routine', total=args.max_samples, position=0, leave=True)

data processing routine:   0%|          | 0/10 [00:00<?, ?it/s]

In [ ]:
all_data = []

for sample in json_data:
    if len(all_data) >= args.max_samples: break

    query = clean_text(sample['query'])
    document = clean_text(sample['text'])

    if len(query) > 512 : continue

    if len(document) > 512:
      subsections = split_paragraph_list(document)

      # document = text_similarity(query, subsections)
      document = lexical_text_similarity(query, subsections)[0]

    all_data.append((query, document))
    progress_bar.update()

In [ ]:
df = pd.DataFrame(all_data, columns=['query', 'document'])

df.head()

,query,document
0,Seniors' Retirement Recovery Act of 2002 - Ame...,SECTION 1. SHORT TITLE. This Act may be cited ...
1,Independent Ethics Commission Act of 2007 - Es...,SECTION 1. SHORT TITLE. This Act may be cited ...
2,Amends the Help America Vote Act of 2002 to re...,STATE OR LOCAL GOVERNMENT ENTITY. (a) In Gener...
3,America Rx Act of 2003 - Directs the Secretary...,to those residents who are without access to d...
4,Global Service Fellowship Program Act of 2007 ...,Volunteers for Prosperity program administered...

In [ ]:
df['split'] = 'train'

num_train_rows = int(len(df) * (1 - args.train_split)) - 1
df.loc[:num_train_rows, 'split'] = 'val'

df.head()

,query,document,split
0,Seniors' Retirement Recovery Act of 2002 - Ame...,SECTION 1. SHORT TITLE. This Act may be cited ...,val
1,Independent Ethics Commission Act of 2007 - Es...,SECTION 1. SHORT TITLE. This Act may be cited ...,val
2,Amends the Help America Vote Act of 2002 to re...,STATE OR LOCAL GOVERNMENT ENTITY. (a) In Gener...,val
3,America Rx Act of 2003 - Directs the Secretary...,to those residents who are without access to d...,train
4,Global Service Fellowship Program Act of 2007 ...,Volunteers for Prosperity program administered...,train