# For preparing fine-tuning data for MLM (Masked Language Modelling)

In [ ]:
!pip3 install argparse
!pip3 install numpy
!pip3 install pandas
# !pip3 install transformers
!pip3 install nltk
!pip3 install torch

Collecting argparse
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.66.1)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)

In [ ]:
import os
import json
import re
import string
import random
import time
import datetime
import numpy as np
import pandas as pd
from argparse import Namespace

# from transformers import BertTokenizer

import torch
import random
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Prepare configurations for data preparation

In [ ]:
args = Namespace(
    raw_data_filename = 'aus_sum_cases_train.json',
    raw_data_path = "/content/drive/MyDrive/Colab_Notebooks/CS4099-LegalNLP/raw_data/",
    processed_data_path = "/content/drive/MyDrive/Colab_Notebooks/CS4099-LegalNLP/processed_data/",
    max_segment_length = 256,
    max_samples = 3500,
    mode = 'a', # a : append, w : write,
    train_split = 0.7,
)

## Ingest Raw Data

Format :
{\
    &nbsp;&nbsp; query\
    &nbsp;&nbsp; text \
    &nbsp;&nbsp; topic_label\
    &nbsp;&nbsp; secondary_query\
    &nbsp;&nbsp; label\
}

### Using NLTK for tokenization

In [ ]:
def mask_tokens(sentence):
    '''
        Takes a list of tokens (sentence) and masks a percentage of them by
        replacing a percentage of tokens with [MASK] token

        Arguments:
            sentence : [String, String, ...]
    '''
    num_tokens = len(sentence)
    num_to_mask = max(1, int(num_tokens * masking_percentage))
    indices_to_mask = random.sample(range(num_tokens), num_to_mask)

    masked_sentence = sentence.copy()
    original_tokens = []

    for idx in indices_to_mask:
        original_tokens.append(masked_sentence[idx])
        masked_sentence[idx] = mask_token

    return [masked_sentence, original_tokens]

In [ ]:
# Open and parse file

with open(args.raw_data_path + args.raw_data_filename, 'r') as json_file:
    json_data = json.load(json_file)

In [ ]:
# extract sentences from data
all_sentences = []

counter = 0

for item in json_data:
    counter += 1
    if len(all_sentences) >= args.max_samples: break

    sentences = nltk.sent_tokenize(item['text']) + nltk.sent_tokenize(item['query'])

    i = 0
    while i < len(sentences):
        sentence = sentences[i]
#         i = i + 5 # every 5 sentences for more uniform coverage of documents in data
        i += 1

        # if sentence/sample larger than 512 characters
        if len(sentence) > 512 or len(sentence.split(' ')) <= 10: continue
        # if we've reached maximum number of samples needed
        if len(all_sentences) >= args.max_samples: break

        all_sentences.append(sentence)

print(counter)
print(len(all_sentences))

116
3500

## Process/Prepare Raw Data

In [ ]:
df = pd.DataFrame(all_sentences, columns=['sentence'])

df.head()

                                            sentence
0  This Act may be cited as the ``Border Hospital...
1  The Congress finds as follows:\n            (1...
2  (2) The Immigration and Naturalization Service...
3  (4) The Southwest border region is ill-equippe...
4  (5) The Southwest border region has been desig...

In [ ]:
df['split'] = 'train'

num_train_rows = int(len(df) * (1 - args.train_split)) - 1
df.loc[:num_train_rows, 'split'] = 'val'

df.head()

                                            sentence split
0  This Act may be cited as the ``Border Hospital...   val
1  The Congress finds as follows:\n            (1...   val
2  (2) The Immigration and Naturalization Service...   val
3  (4) The Southwest border region is ill-equippe...   val
4  (5) The Southwest border region has been desig...   val

In [ ]:
# Save data to file
df.to_csv(args.processed_data_path + '/sentences.csv', mode=args.mode)